stages:
  - test

default:
  tags:
    - fusion-shared-runner-docker

variables:
  POSTGRES_USER: mole_user
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: mole
  GO_VERSION: "1.23.6"
  MIGRATE_VERSION: "4.18.1"

services:
  - name: postgis/postgis:16-3.5
    alias: postgres

before_script:
  - apt-get update && apt-get install -y curl tar build-essential
  - echo "Installing Go $GO_VERSION..."
  - curl -OL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
  - rm -rf /usr/local/go && tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
  - export PATH="/usr/local/go/bin:$PATH"
  - echo 'export PATH="/usr/local/go/bin:$PATH"' >> ~/.bashrc
  - go version
  - echo "Installing golang-migrate..."
  - curl -L https://github.com/golang-migrate/migrate/releases/download/v${MIGRATE_VERSION}/migrate.linux-amd64.tar.gz | tar xvz
  - mv migrate /usr/local/bin/migrate
  - which migrate
  - make create-postgres
  - make createdb
  - echo "Running database migrations..."
  - make migrateup


test:
  stage: test
  image: ubuntu:22.04
  script:
    - echo "Running tests..."
    - make test