// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Context struct {
	// Unique ID for the context record
	ID int64 `json:"id"`
	// Reference to the associated entity
	EntityID uuid.UUID `json:"entity_id"`
	// High-level classification (e.g., 'event-type', 'vehicle', 'sensor')
	EntityType string `json:"entity_type"`
	// A detailed categorization or model within the high-level classification (e.g., 'Detection', 'Fixed-wing', 'Weather-station')
	SpecificType string `json:"specific_type"`
	// Timestamp for when the context record was created
	CreatedAt time.Time `json:"created_at"`
}

type Entity struct {
	// Unique identifier for the entity
	EntityID uuid.UUID `json:"entity_id"`
	// Display name for the entity
	Name string `json:"name"`
	// Human-readable description
	Description string `json:"description"`
}

type GeoDetail struct {
	// Unique ID for the geo detail record
	GeoID int64 `json:"geo_id"`
	// Reference to the associated instance
	InstanceID int64 `json:"instance_id"`
	// Geospatial point representation of the entity.
	GeoPoint interface{} `json:"geo_point"`
	// Geospatial line representation of the entity.
	GeoLine interface{} `json:"geo_line"`
	// Geospatial polygon representation of the entity.
	GeoPolygon interface{} `json:"geo_polygon"`
	// Geospatial ellipse representation of the entity.
	GeoEllipse interface{} `json:"geo_ellipse"`
	// Geospatial ellipsoid representation of the entity.
	GeoEllipsoid interface{} `json:"geo_ellipsoid"`
}

type Instance struct {
	// Unique ID for the instance record
	ID int64 `json:"id"`
	// Reference to the associated entity
	EntityID uuid.UUID `json:"entity_id"`
	// Client-provided timestamp for when the instance data was created.
	CreatedAt time.Time `json:"created_at"`
	// Server-generated timestamp for last modification.
	ModifiedAt time.Time `json:"modified_at"`
}

type Position struct {
	// Unique ID for the position record
	PositionID int64 `json:"position_id"`
	// Reference to the associated instance
	InstanceID int64 `json:"instance_id"`
	// WGS84 geodetic latitude in decimal degrees.
	LatitudeDegrees float64 `json:"latitude_degrees"`
	// WGS84 longitude in decimal degrees.
	LongitudeDegrees float64 `json:"longitude_degrees"`
	// Heading in degrees.
	HeadingDegrees sql.NullFloat64 `json:"heading_degrees"`
	// Altitude as height above ellipsoid (WGS84), in meters.
	AltitudeHaeMeters sql.NullFloat64 `json:"altitude_hae_meters"`
	// Speed as the magnitude of velocity, in meters per second.
	SpeedMps sql.NullFloat64 `json:"speed_mps"`
}

type Provenance struct {
	// Unique ID for the provenance record
	ID int64 `json:"id"`
	// Reference to the entity associated with this provenance record
	EntityID uuid.UUID `json:"entity_id"`
	// Optional name or identifier for the source system (e.g., 'gps', 'telemetry')
	DataType sql.NullString `json:"data_type"`
	// Optional name for the entity that generated this entity. Used for events such as detections or tracks
	SourceName sql.NullString `json:"source_name"`
	// Integration source used for which system provided the data (e.g., 'TAK')
	IntegrationSource string `json:"integration_source"`
	// Last modification time according to the source system
	SourceUpdateTime time.Time `json:"source_update_time"`
	// Timestamp for when the provenance record was created
	CreatedAt time.Time `json:"created_at"`
}
