// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEntity(ctx context.Context, arg CreateEntityParams) (CreateEntityRow, error)
	DeleteEntity(ctx context.Context, entityID uuid.UUID) error
	GetEntitiesByNames(ctx context.Context, dollar_1 []string) ([]GetEntitiesByNamesRow, error)
	GetEntity(ctx context.Context, entityID uuid.UUID) (Entity, error)
	GetEntityByNameAndIntegrationSource(ctx context.Context, arg GetEntityByNameAndIntegrationSourceParams) (GetEntityByNameAndIntegrationSourceRow, error)
	GetEntityByNames(ctx context.Context, name string) ([]GetEntityByNamesRow, error)
	InsertLocation(ctx context.Context, arg InsertLocationParams) (int64, error)
	InsertPosition(ctx context.Context, arg InsertPositionParams) error
	ListEntities(ctx context.Context, arg ListEntitiesParams) ([]ListEntitiesRow, error)
	UpdateEntityByName(ctx context.Context, arg UpdateEntityByNameParams) (Entity, error)
	UpdateEntityIntegrationSourceByNameAndSource(ctx context.Context, arg UpdateEntityIntegrationSourceByNameAndSourceParams) (UpdateEntityIntegrationSourceByNameAndSourceRow, error)
}

var _ Querier = (*Queries)(nil)
