// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error)
	DeleteEntity(ctx context.Context, entityID uuid.UUID) error
	GetEntitiesByNames(ctx context.Context, dollar_1 []string) ([]Entity, error)
	GetEntity(ctx context.Context, entityID uuid.UUID) (Entity, error)
	GetEntityByName(ctx context.Context, name string) (Entity, error)
	// ensures that the input parameter is explicitly cast as a PostgreSQL array of text
	ListEntities(ctx context.Context, arg ListEntitiesParams) ([]Entity, error)
	// Return the entity ID, location ID, and position ID
	RegisterEntityWithPosition(ctx context.Context, arg RegisterEntityWithPositionParams) (RegisterEntityWithPositionRow, error)
	UpdateEntityByName(ctx context.Context, arg UpdateEntityByNameParams) (Entity, error)
}

var _ Querier = (*Queries)(nil)
